services:
  # --- MailHog (Email Testing) ---
  mailhog:
    image: jcalonso/mailhog:latest
    container_name: mailhog
    platform: linux/arm64
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - danxils-network

  # --- Automation ---
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports: [ "5678:5678" ]
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    networks: [ "danxils-network" ]

networks:
  danxils-network:
    external: true
    name: voidtracker_danxils-network
