version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: danxils-postgres
    environment:
      POSTGRES_USER: danxils
      POSTGRES_PASSWORD: danxils123
      POSTGRES_DB: danxils_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - danxils-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: danxils-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - danxils-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: danxils-kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - danxils-network

  mailhog:
    image: mailhog/mailhog
    container_name: danxils-mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - danxils-network

volumes:
  postgres_data:
    external: true
    name: tes_postgres_data

networks:
  danxils-network:
    driver: bridge
