# ARCHITEKTURA: Konfiguracja serwera Prometheus.
# Definiuje, jakie endpointy (nasze mikroserwisy) mają być monitorowane (scrape'owane).
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'danxils_microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'iam-app:8081'
          - 'order-service:8082'
          - 'planning-service:8083'
          - 'analytics-service:8084'
          - 'tracking-service:8085'