name: danxils_mobile_app
description: "DANXILS Driver App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  dio: ^5.4.0
  intl: ^0.19.0
  signature: ^5.4.0
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  lucide_icons: ^0.300.0
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
